// <auto-generated />
using System;
using Catalogo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Catalogo.Data.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20210809030830_AdicionarProdutos")]
    partial class AdicionarProdutos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Catalogo.Domain.Models.Produto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("955bd18e-9050-44ad-9bd7-8cc7fc410d53"),
                            Estoque = 10,
                            Nome = "Produto de teste 1",
                            Valor = 100m
                        },
                        new
                        {
                            Id = new Guid("b492e203-0209-4110-b373-17b0201c6f52"),
                            Estoque = 20,
                            Nome = "Produto de teste 2",
                            Valor = 200m
                        },
                        new
                        {
                            Id = new Guid("424cd108-6702-4fa4-ae5f-d5d736480f85"),
                            Estoque = 30,
                            Nome = "Produto de teste 3",
                            Valor = 300m
                        },
                        new
                        {
                            Id = new Guid("4d709a0b-fc55-488e-b902-707cc10d06a2"),
                            Estoque = 40,
                            Nome = "Produto de teste 4",
                            Valor = 400m
                        },
                        new
                        {
                            Id = new Guid("0aca01f3-aaac-4b6b-9c2b-f675868ab8d2"),
                            Estoque = 50,
                            Nome = "Produto de teste 5",
                            Valor = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
